language: php

php:
  - 5.5

matrix:
  fast_finish: true

before_script:
  - echo "extension = zmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - printf "yes\nyes\nno\nyes\n" | pecl install pecl_http-1.7.6
  - composer self-update
  - mkdir test
  - cd test
  - echo "eyJtaW5pbXVtLXN0YWJpbGl0eSI6ICJkZXYifQo=" | base64 -d  > composer.json
  - composer require "photon/photon:dev-develop"
  - composer require "photon/template-markdown:dev-master"
  - cp vendor/photon/template-markdown/phpunit.xml .
  
script: phpunit -c phpunit.xml

